Repository team-popo-world/child-popo-world-front, pull requests merged in 2025-06, with the labels that each got.

#16 [SETUP]: 리액트 쿼리 세팅
  package-lock.json
  package.json
  src/App.tsx
  src/lib/react-query/use-data-query.ts
  src/page/test/index.tsx
Labels: ⚙️ setup, 은규

#22 [UI] 퀘스트 첫 페이지 ( 부모 퀘스트, 일일 퀘스트 선택 ) 퍼블리싱
  src/App.tsx
  src/module/quest/template/DailyQuestDetailTemplate.tsx
  src/module/quest/template/ParentQuestDetailTemplate.tsx
  src/module/quest/template/index.tsx
  src/page/quest/detail/index.tsx
  src/page/quest/index.tsx
Labels: 은비, 🎨 ui

#26 [UI] UI 퍼블리싱 : 포포 키우기 페이지 퍼블리싱 #20
  package-lock.json
  package.json
  src/assets/image/raising/raising_apple.webp
  src/assets/image/raising/raising_background.webp
  src/assets/image/raising/raising_bread.webp
  src/assets/image/raising/raising_broccoli.webp
  src/assets/image/raising/raising_carrot.webp
  src/assets/image/raising/raising_character1.webp
  src/assets/image/raising/raising_character2.webp
  src/assets/image/raising/raising_character3.webp
  src/assets/image/raising/raising_character4.webp
  src/assets/image/raising/raising_character5.webp
  src/assets/image/raising/raising_fish.webp
  src/assets/image/raising/raising_nest.webp
  src/assets/image/raising/raising_watermelon.webp
  src/module/raising/template/index.tsx
  src/page/auth/login/index.tsx
  src/page/auth/register/index.tsx
  src/page/raising/index.tsx
Labels: ✨feat, 현기, 🎨 ui

#30 [REFACTOR]: font preload, 페이지 preload 삭제
  index.html
  src/App.tsx
  src/assets/font/TJJoyofsinging_WOFF2/TJJoyofsingingB_WOFF2.woff2
  src/assets/font/TJJoyofsinging_WOFF2/TJJoyofsingingEB_WOFF2.woff2
  src/assets/font/TJJoyofsinging_WOFF2/TJJoyofsingingL_WOFF2.woff2
  src/assets/font/TJJoyofsinging_WOFF2/TJJoyofsingingM_WOFF2.woff2
  src/assets/image/investing-game/little_pig/little_pig_close.webp
  src/components/button/BackArrow.tsx
  src/index.css
  src/lib/api/axios.ts
  src/lib/api/invest-game/investChapterApi.tsx
  src/lib/api/invest-game/investClearAPi.tsx
  src/lib/api/invest-game/investTurnUpdate.tsx
  src/lib/api/investClearAPi.tsx
  src/lib/api/investTurnUpdate.tsx
  src/lib/constants/constants.ts
  src/lib/context/modal-context.tsx
  src/module/investing-game/component/little-pig-component/game-out-modal.tsx
  src/module/investing-game/component/little-pig-component/game-play-pig-card.tsx
  src/module/investing-game/component/little-pig-component/news-box.tsx
  src/module/investing-game/component/little-pig-component/turn-finish-pig-card.tsx
  src/module/investing-game/template/game-end-template.tsx
  src/module/investing-game/template/game-play-template.tsx
  src/module/investing-game/template/game-start-template.tsx
  src/module/investing-game/template/little-pig-template/game-end.tsx
  src/module/investing-game/template/little-pig-template/game-play-turn-finish.tsx
  src/module/investing-game/template/little-pig-template/game-play.tsx
  src/module/investing-game/template/little-pig-template/game-start-explain.tsx
  src/module/investing-game/template/little-pig-template/game-start.tsx
  src/page/investing/game/index.tsx
  src/page/main/index.tsx
Labels: ♻️ refactor, 은규

#33 [FIX] 패키지 오류 및 라우팅 경로 수정
  package-lock.json
  src/App.tsx
Labels: 🔧 fix

#34 [UI]: 마켓 페이지 퍼블리싱
  src/App.tsx
  src/index.css
  src/lib/constants/constants.ts
  src/module/market/components/InventoryModal.tsx
  src/module/market/components/Poni.tsx
  src/module/market/components/PurchaseModal.tsx
  src/module/market/components/SpeechBubble.tsx
  src/module/market/components/WoodTitle.tsx
  src/module/market/template/index.tsx
  src/module/market/template/inventory.tsx
  src/module/market/template/npc-shop.tsx
  src/module/market/template/parent-shop.tsx
  src/page/main/index.tsx
  src/page/market/index.tsx
  src/page/market/inventory/index.tsx
  src/page/market/npc-shop/index.tsx
  src/page/market/parent-shop/index.tsx
Labels: ✨feat, 은규

#39 [FEAT] 퀘스트 백엔드 api 연동
  src/module/quest/components/QuestCard.tsx
  src/module/quest/template/QuestDetailTemplate.tsx
  src/module/quest/types/quest.ts
  src/page/quest/detail/index.tsx
Labels: ✨feat, 은비

#43 [REFACTOR]: 로그 현재 시작시간 업데이트
  src/lib/api/axios.ts
  src/lib/api/invest-game/investClearAPi.tsx
  src/lib/api/invest-game/investTurnUpdate.tsx
  src/page/investing/game/index.tsx
Labels: ♻️ refactor, 은규

#44 [UI]: 출석체크 페이지
  src/lib/constants/constants.ts
  src/module/attandance/template/index.tsx
Labels: 은규, 🎨 ui

#46 [UI] 감정일기 목록 페이지, 작성 페이지 퍼블리싱
  package-lock.json
  src/App.tsx
  src/module/emotionDiary/components/DiaryCard.tsx
  src/module/emotionDiary/dummy/diaryDummy.ts
  src/module/emotionDiary/template/diaryWrite.tsx
  src/module/emotionDiary/template/index.tsx
  src/module/emotionDiary/types/diary.ts
  src/page/emotionDiary/index.tsx
  src/page/emotionDiary/write/index.tsx
Labels: ✨feat, 은비, 🎨 ui

#51 [REFACTOR]: 모의투자 태그 추가
  src/lib/api/axios.ts
  src/lib/api/invest-game/investTurnUpdate.tsx
  src/page/investing/game/index.tsx
Labels: ♻️ refactor, 은규

#53 [UI] : 저축통장 달력 UI 스타일 변경
  .gitignore
  src/lib/api/axios.ts
  src/page/savings/index.tsx
Labels: 현기, 🎨 ui

#56 [FEAT] 감정일기 페이지 백엔드 api 연동
  src/module/emotionDiary/components/DiaryCard.tsx
  src/module/emotionDiary/components/writeLimitModal.tsx
  src/module/emotionDiary/constants/emotionList.ts
  src/module/emotionDiary/dummy/diaryDummy.ts
  src/module/emotionDiary/template/diaryWrite.tsx
  src/module/emotionDiary/template/index.tsx
  src/module/emotionDiary/types/diary.ts
  src/page/emotionDiary/index.tsx
  src/page/emotionDiary/write/index.tsx
Labels: ✨feat, 은비, 🎨 ui

#57 [FEAT]: 로그인 백엔드 _
  src/App.tsx
  src/components/auth/ProtectedRouter.tsx
  src/lib/api/axios.ts
  src/lib/zustand/store.ts
  src/module/main/template/index.tsx
  src/page/auth/login/index.tsx
Labels: ✨feat, 은규

#66 [FEAT]: 포인트 전역관리, 컴포넌트 추가
  src/components/user/NameAndPoint.tsx
  src/lib/api/attandance/attendance.ts
  src/lib/api/axios.ts
  src/lib/zustand/store.ts
  src/module/attandance/template/index.tsx
  src/module/main/template/index.tsx
  src/module/market/template/index.tsx
  src/module/market/template/inventory.tsx
  src/module/market/template/npc-shop.tsx
  src/module/market/template/parent-shop.tsx
  src/page/auth/login/index.tsx
Labels: ✨feat

#68 [FEAT] : 회원가입페이지 뒤로가기 추가
  src/page/auth/register/index.tsx
Labels: ✨feat

#70 [UI] 투자 페이지 애니메이션 추가 및 ui 변경
  src/lib/constants/constants.ts
  src/module/investing/template/index.tsx
  src/page/investing/index.tsx
  src/page/quest/detail/index.tsx
Labels: 은비, 🎨 ui

#80 [FEAT] : 저축 통장 페이지 백엔드 연동
  package-lock.json
  package.json
  src/page/auth/login/index.tsx
  src/page/savings/index.tsx
Labels: ✨feat, 현기

#81 Pref/#74 imgae
  index.html
  src/App.tsx
  src/assets/image/common/common_coin.webp
  src/assets/image/common/common_name.webp
  src/assets/image/login/login_background.png
  src/assets/image/main/main_attendance.webp
  src/assets/image/main/main_background.webp
  src/assets/image/main/main_emotions_diary.webp
  src/assets/image/main/main_investing.webp
  src/assets/image/main/main_market.webp
  src/assets/image/main/main_poni.webp
  src/assets/image/main/main_quest.webp
  src/assets/image/main/main_quiz.webp
  src/assets/image/main/main_raising.webp
  src/assets/image/main/main_savings.webp
  src/assets/image/quest/quest_popo.webp
  src/assets/image/raising/raising_apple.webp
  src/assets/image/raising/raising_background.webp
  src/assets/image/raising/raising_bread.webp
  src/assets/image/raising/raising_broccoli.webp
  src/assets/image/raising/raising_carrot.webp
  src/assets/image/raising/raising_character1.webp
  src/assets/image/raising/raising_character2.webp
  src/assets/image/raising/raising_character3.webp
  src/assets/image/raising/raising_character4.webp
  src/assets/image/raising/raising_character5.webp
  src/assets/image/raising/raising_fish.webp
  src/assets/image/raising/raising_nest.webp
  src/assets/image/raising/raising_watermelon.webp
  src/assets/image/register/register_background.png
  src/components/auth/ProtectedRouter.tsx
  src/index.css
  src/lib/constants/constants.ts
  src/lib/type/preloadType.ts
  src/main.tsx
  src/module/emotionDiary/template/index.tsx
  src/module/investing-game/component/game-component/game-play-stock-card.tsx
  src/module/investing-game/component/game-component/turn-finish-stock-card.tsx
  src/module/investing-game/template/game-template/game-end.tsx
  src/module/investing-game/template/game-template/game-play-turn-finish.tsx
  src/module/investing-game/template/game-template/game-play.tsx
  src/module/market/components/InventoryModal.tsx
  src/module/market/components/Poni.tsx
  src/module/market/components/PurchaseModal.tsx
  src/module/market/template/npc-shop.tsx
  src/module/market/template/parent-shop.tsx
  src/module/quest/template/QuestDetailTemplate.tsx
  src/page/auth/login/index.tsx
  src/page/auth/register/index.tsx
  src/page/main/index.tsx
  src/page/market/index.tsx
  src/page/raising/index.tsx
  src/page/savings/index.tsx
Labels: ✨feat, 은규

#87 [REFACTOR] 퀘스트 코드 리팩토링 및 라벨 추가
  src/components/user/NameAndPoint.tsx
  src/lib/constants/constants.ts
  src/module/main/template/index.tsx
  src/module/quest/components/QuestCard.tsx
  src/module/quest/components/StateChangeModal.tsx
  src/module/quest/template/QuestDetailTemplate.tsx
  src/module/quest/template/index.tsx
  src/module/quest/types/quest.ts
  src/page/quest/detail/index.tsx
Labels: ♻️ refactor, 은비, 🎨 ui

#92 [REFACTOR, FIX]: 모의투자 게임마다 다른 이미지 추가, 결과 다음턴 결과로 수정
  package.json
  src/assets/image/common/back_arrow.webp
  src/assets/image/common/close.webp
  src/components/auth/ProtectedRouter.tsx
  src/components/button/BackArrow.tsx
  src/components/button/SoundButton.tsx
  src/components/icon/CloseIcon.tsx
  src/lib/api/axios.ts
  src/lib/constants/constants.ts
  src/lib/utils/sound.tsx
  src/main.tsx
  src/module/investing-game/component/game-component/border-modal.tsx
  src/module/investing-game/component/game-component/game-out-modal.tsx
  src/module/investing-game/component/game-component/news-box.tsx
  src/module/investing-game/component/game-component/turn-finish-stock-card.tsx
  src/module/investing-game/template/game-end-template.tsx
  src/module/investing-game/template/game-play-template.tsx
  src/module/investing-game/template/game-start-template.tsx
  src/module/investing-game/template/game-template/game-end.tsx
  src/module/investing-game/template/game-template/game-play-turn-finish.tsx
  src/module/investing-game/template/game-template/game-play.tsx
  src/module/investing-game/template/game-template/game-start-explain.tsx
  src/module/investing-game/template/game-template/game-start.tsx
  src/module/main/template/index.tsx
  src/page/auth/login/index.tsx
  src/page/investing/game/index.tsx
  src/page/main/index.tsx
Labels: ♻️ refactor, 은규, 🔧 fix

#93 [FEAT] : 포포 키우기 백엔드 연동
  src/assets/image/common/common_coin.webp
  src/assets/image/common/common_name.webp
  src/assets/image/login/login_background.png
  src/assets/image/main/main_attendance.webp
  src/assets/image/main/main_background.webp
  src/assets/image/main/main_emotions_diary.webp
  src/assets/image/main/main_investing.webp
  src/assets/image/main/main_market.webp
  src/assets/image/main/main_poni.webp
  src/assets/image/main/main_quest.webp
  src/assets/image/main/main_quiz.webp
  src/assets/image/main/main_raising.webp
  src/assets/image/main/main_savings.webp
  src/assets/image/quest/quest_popo.webp
  src/assets/image/raising/raising_apple.webp
  src/assets/image/raising/raising_background.webp
  src/assets/image/raising/raising_bread.webp
  src/assets/image/raising/raising_broccoli.webp
  src/assets/image/raising/raising_carrot.webp
  src/assets/image/raising/raising_character1.webp
  src/assets/image/raising/raising_character2.webp
  src/assets/image/raising/raising_character3.webp
  src/assets/image/raising/raising_character4.webp
  src/assets/image/raising/raising_character5.webp
  src/assets/image/raising/raising_fish.webp
  src/assets/image/raising/raising_nest.webp
  src/assets/image/raising/raising_watermelon.webp
  src/assets/image/register/register_background.png
  src/page/raising/index.tsx
Labels: ✨feat, 현기

#98 [FEAT, REFACTOR]: 포인트 모달들 추가, 포인트 관련 기능 추가, 수정
  package.json
  src/components/auth/ProtectedRouter.tsx
  src/components/button/SoundButton.tsx
  src/components/loading/ToRasingLandLoading2.tsx
  src/components/lottie/Confetti.json
  src/components/modal/Modal.tsx
  src/components/modal/NoPointModal.tsx
  src/components/modal/PointModal.tsx
  src/components/user/NameAndPoint.tsx
  src/lib/api/attandance/attendance.ts
  src/lib/api/axios.ts
  src/lib/api/invest-game/investClearAPi.tsx
  src/lib/constants/constants.ts
  src/lib/utils/sound.tsx
  src/lib/zustand/authStore.ts
  src/lib/zustand/soundStore.ts
  src/module/attandance/template/index.tsx
  src/module/emotionDiary/template/diaryWrite.tsx
  src/module/emotionDiary/template/index.tsx
  src/module/investing-game/component/border-modal.tsx
  src/module/investing-game/component/game-out-modal.tsx
  src/module/investing-game/component/game-play-stock-card.tsx
  src/module/investing-game/component/news-box.tsx
  src/module/investing-game/component/stock-description.tsx
  src/module/investing-game/component/turn-finish-stock-card.tsx
  src/module/investing-game/template/game-start-template.tsx
  src/module/investing-game/template/game-template/game-end.tsx
  src/module/investing-game/template/game-template/game-play-turn-finish.tsx
  src/module/investing-game/template/game-template/game-play.tsx
  src/module/investing-game/template/game-template/game-start-explain.tsx
  src/module/investing-game/template/game-template/game-start.tsx
  src/module/investing/components/game-start-modal.tsx
  src/module/investing/template/index.tsx
  src/module/market/components/InventoryModal.tsx
  src/module/market/components/Poni.tsx
  src/module/market/components/PurchaseModal.tsx
  src/module/market/template/index.tsx
  src/module/market/template/inventory.tsx
  src/module/market/template/npc-shop.tsx
  src/module/market/template/parent-shop.tsx
  src/module/quest/template/QuestDetailTemplate.tsx
  src/module/quest/template/index.tsx
  src/page/auth/login/index.tsx
  src/page/emotionDiary/index.tsx
  src/page/investing/game/index.tsx
  src/page/investing/index.tsx
  src/page/main/index.tsx
  src/page/market/index.tsx
  src/page/market/inventory/index.tsx
  src/page/market/npc-shop/index.tsx
  src/page/market/parent-shop/index.tsx
  src/page/quest/complete/QuestComplete.tsx
  src/page/quest/detail/index.tsx
  src/page/quest/index.tsx
  src/page/raising/index.tsx
  src/page/savings/index.tsx
  src/page/test/reatQueryText.tsx
  vercel.json
Labels: ✨feat, ♻️ refactor, 은규

#97 [FEAT]: 소리추가
  package.json
  src/components/button/SoundButton.tsx
  src/components/loading/ToRasingLandLoading2.tsx
  src/components/modal/Modal.tsx
  src/components/user/NameAndPoint.tsx
  src/lib/utils/sound.tsx
  src/lib/zustand/soundStore.ts
  src/module/emotionDiary/template/diaryWrite.tsx
  src/module/emotionDiary/template/index.tsx
  src/module/investing-game/component/border-modal.tsx
  src/module/investing-game/component/game-out-modal.tsx
  src/module/investing-game/component/game-play-stock-card.tsx
  src/module/investing-game/component/game-start-modal.tsx
  src/module/investing-game/component/news-box.tsx
  src/module/investing-game/component/stock-description.tsx
  src/module/investing-game/component/turn-finish-stock-card.tsx
  src/module/investing-game/template/game-start-template.tsx
  src/module/investing-game/template/game-template/game-end.tsx
  src/module/investing-game/template/game-template/game-play-turn-finish.tsx
  src/module/investing-game/template/game-template/game-play.tsx
  src/module/investing-game/template/game-template/game-start-explain.tsx
  src/module/investing-game/template/game-template/game-start.tsx
  src/module/market/components/InventoryModal.tsx
  src/module/market/components/PurchaseModal.tsx
  src/module/market/template/index.tsx
  src/module/market/template/inventory.tsx
  src/module/market/template/npc-shop.tsx
  src/module/market/template/parent-shop.tsx
  src/module/quest/template/QuestDetailTemplate.tsx
  src/module/quest/template/index.tsx
  src/page/emotionDiary/index.tsx
  src/page/investing/game/index.tsx
  src/page/market/index.tsx
  src/page/market/inventory/index.tsx
  src/page/market/npc-shop/index.tsx
  src/page/market/parent-shop/index.tsx
  src/page/quest/complete/QuestComplete.tsx
  src/page/quest/detail/index.tsx
  src/page/quest/index.tsx
  src/page/raising/index.tsx
  src/page/savings/index.tsx
  src/page/test/reatQueryText.tsx
  vercel.json
Labels: ✨feat, 은규

#100 [FIX] : 포포키우기 productId 수정
  src/page/raising/index.tsx
Labels: 현기, 🔧 fix

#104 [PREF, REFACTOR] : 탄스택 쿼리 적용해서 지금 이제 깜빡임 다사라짐, 부족한 부분들 거의 다 해결함
  src/App.tsx
  src/components/modal/NoPointModal.tsx
  src/components/modal/PointModal.tsx
  src/lib/api/emotion/getDiary.ts
  src/lib/api/emotion/postDiary.ts
  src/lib/api/invest-game/getChapterData.tsx
  src/lib/api/invest-game/postEndGame.tsx
  src/lib/api/invest-game/postSendTurnData.tsx
  src/lib/api/quest/getQuest.ts
  src/lib/api/user/getUser.ts
  src/lib/constants/constants.ts
  src/lib/react-query/use-data-query.ts
  src/lib/utils/getSpaceFromImage.ts
  src/lib/utils/utils.ts
  src/lib/zustand/authStore.ts
  src/module/attandance/template/index.tsx
  src/module/emotionDiary/components/AlretModal.tsx
  src/module/emotionDiary/template/diaryWrite.tsx
  src/module/emotionDiary/template/index.tsx
  src/module/investing-game/template/game-template/game-end.tsx
  src/module/investing/template/index.tsx
  src/module/market/template/inventory.tsx
  src/module/market/template/npc-shop.tsx
  src/module/market/template/parent-shop.tsx
  src/module/quest/components/StateChangeModal.tsx
  src/module/quest/template/QuestDetailTemplate.tsx
  src/page/attandance/index.tsx
  src/page/auth/login/index.tsx
  src/page/emotionDiary/index.tsx
  src/page/emotionDiary/write/index.tsx
  src/page/investing/game/index.tsx
  src/page/investing/index.tsx
  src/page/main/index.tsx
  src/page/market/inventory/index.tsx
  src/page/market/npc-shop/index.tsx
  src/page/market/parent-shop/index.tsx
  src/page/quest/detail/index.tsx
Labels: ✨feat, ♻️ refactor, 은규

#102 [REFACTOR]: 부족한 부분들 채우기
  src/components/modal/PointModal.tsx
  src/lib/constants/constants.ts
  src/module/attandance/template/index.tsx
  src/module/emotionDiary/template/index.tsx
  src/module/investing-game/template/game-template/game-end.tsx
  src/module/investing/template/index.tsx
  src/module/quest/template/QuestDetailTemplate.tsx
  src/page/attandance/index.tsx
  src/page/emotionDiary/index.tsx
  src/page/investing/game/index.tsx
  src/page/investing/index.tsx
  src/page/main/index.tsx
Labels: ♻️ refactor, 은규

#108 [REFACTOR] 탄스택쿼리
  src/lib/api/invest-game/postEndGame.tsx
  src/lib/api/quest/postQuestState.ts
  src/page/investing/game/index.tsx
  src/page/investing/index.tsx
  src/page/market/parent-shop/index.tsx
  src/page/quest/detail/index.tsx
Labels: ♻️ refactor, 은규

#111 [UI] 퀴즈페이지 ui 및 api 연동
  package.json
  src/App.tsx
  src/index.css
  src/lib/constants/constants.ts
  src/module/quest/dummy/dailyDummy.ts
  src/module/quiz/template/QuizAnswerTemplate.tsx
  src/module/quiz/template/QuizCompleteTemplate.tsx
  src/module/quiz/template/QuizPlayTemplate.tsx
  src/module/quiz/template/QuizSelectTemplate.tsx
  src/module/quiz/template/QuizTopicSelectTemplate.tsx
  src/module/quiz/template/index.tsx
  src/page/quiz/index.tsx
  src/page/quiz/level-select/index.tsx
  src/page/quiz/quiz-play/index.tsx
  src/page/quiz/topic-select/index.tsx
Labels: ✨feat, 은비, 🎨 ui

#110 [REFACTOR] : api 파일 분리, localstorage 저장키 형식 수정
  src/lib/api/auth/login.ts
  src/lib/api/auth/register.ts
  src/lib/api/raising/raising.ts
  src/lib/api/savings/savings.ts
  src/lib/zustand/authStore.ts
  src/page/auth/login/index.tsx
  src/page/auth/register/index.tsx
  src/page/raising/index.tsx
  src/page/savings/index.tsx
Labels: ♻️ refactor, 현기

#113 [CHORE] : 배포 설정
  package.json
  src/lib/api/axios.ts
  src/page/quiz/quiz-play/index.tsx
  src/page/savings/index.tsx
  vercel.json
  vite.config.ts
Labels: chore

#117 [FEAT]: 음성 추가
  src/assets/sound/tutorial/diary_tts_“포포는 네 마음이 궁금해! 같이 써보자~”_2025-06-27.wav
  src/assets/sound/tutorial/inventory_tts_“여긴 너만의 창고야. 모아둔 걸 꺼내서 쓸 수 있어~!”_2025-06-28 (1).wav
  src/assets/sound/tutorial/invest_tts_“모의투자 섬 도착! 오늘은 어디에 투자해볼까_”_2025-06-27.wav
  src/assets/sound/tutorial/quest_tts_“작은 약속~ 지켜볼까_ 오늘도 멋지게 도전!”_2025-06-27.wav
  src/assets/sound/tutorial/rasing_tts_“포포가 기다리고 있어~ 먹이 주러 가보자!”_2025-06-27.wav
  src/assets/sound/tutorial/rasing_tts“배고픈 포포 기다리는 중~ 냠냠~ 먹이 주러 가자”_2025-06-28.wav
  src/assets/sound/tutorial/savings_tts_“차곡차곡~ 저축 섬 도착! 오늘도 모아볼까_”_2025-06-27.wav
  src/lib/utils/sound.tsx
  src/module/main/template/Tutorial.tsx
  src/page/attandance/index.tsx
  src/page/emotionDiary/index.tsx
  src/page/investing/game/index.tsx
  src/page/investing/index.tsx
  src/page/main/index.tsx
  src/page/market/index.tsx
  src/page/market/inventory/index.tsx
  src/page/market/parent-shop/index.tsx
  src/page/quest/index.tsx
  src/page/quiz/index.tsx
  src/page/raising/index.tsx
  src/page/savings/index.tsx
Labels: ✨feat, 은규

#119 [UI] ui 디테일 수정 및 로직 변경
  src/assets/image/common/common_coin.webp
  src/assets/image/common/common_name.webp
  src/assets/image/login/login_background.png
  src/assets/image/main/main_attendance.webp
  src/assets/image/main/main_background.webp
  src/assets/image/main/main_emotions_diary.webp
  src/assets/image/main/main_investing.webp
  src/assets/image/main/main_market.webp
  src/assets/image/main/main_poni.webp
  src/assets/image/main/main_quest.webp
  src/assets/image/main/main_quiz.webp
  src/assets/image/main/main_raising.webp
  src/assets/image/main/main_savings.webp
  src/assets/image/quest/quest_popo.webp
  src/assets/image/raising/raising_apple.webp
  src/assets/image/raising/raising_background.webp
  src/assets/image/raising/raising_bread.webp
  src/assets/image/raising/raising_broccoli.webp
  src/assets/image/raising/raising_carrot.webp
  src/assets/image/raising/raising_character1.webp
  src/assets/image/raising/raising_character2.webp
  src/assets/image/raising/raising_character3.webp
  src/assets/image/raising/raising_character4.webp
  src/assets/image/raising/raising_character5.webp
  src/assets/image/raising/raising_fish.webp
  src/assets/image/raising/raising_nest.webp
  src/assets/image/raising/raising_watermelon.webp
  src/assets/image/register/register_background.png
  src/assets/image/savings/savings_background.webp
  src/assets/image/savings/savings_character.webp
  src/assets/image/savings/savings_star.webp
  src/lib/constants/constants.ts
  src/module/attandance/template/index.tsx
  src/module/emotionDiary/components/AlretModal.tsx
  src/module/emotionDiary/components/writeLimitModal.tsx
  src/module/emotionDiary/constants/emotionList.ts
  src/module/emotionDiary/template/diaryWrite.tsx
  src/module/emotionDiary/template/index.tsx
  src/module/investing/components/Info.tsx
  src/module/investing/template/index.tsx
  src/module/main/template/Tutorial.tsx
  src/module/quest/template/QuestCompleteTemplate.tsx
  src/module/quest/template/index.tsx
  src/page/attandance/index.tsx
Labels: 은비, 🎨 ui

#120 [FEAT]: 알림했음
  index.html
  public/icon.png
  public/manifest.json
  public/sw.js
  src/App.tsx
  src/components/layout/PushNotificationProvider.tsx
  src/lib/api/push/getPublicKey.ts
  src/lib/api/push/postPushMessage.ts
  src/lib/api/push/postSubscribe.ts
  src/lib/utils/pushNotification.ts
  src/lib/utils/push_v2.ts
  src/lib/utils/urlBase64ToUint8Array.ts
  src/lib/utils/utils.ts
  src/lib/zustand/tutorialStore.ts
  src/module/market/template/parent-shop.tsx
  src/page/attandance/index.tsx
  src/page/emotionDiary/write/index.tsx
  src/page/investing/game/index.tsx
  src/page/main/index.tsx
  src/page/market/inventory/index.tsx
  src/page/market/parent-shop/index.tsx
  src/page/quest/detail/index.tsx
  src/page/quiz/quiz-play/index.tsx
  src/page/savings/index.tsx
  vite.config.ts
Labels: ✨feat, 은규

#122 [UI] 시장 및 모의투자 디자인 변경
  src/index.css
  src/lib/constants/constants.ts
  src/module/investing-game/template/game-template/game-end.tsx
  src/module/investing-game/template/game-template/game-start.tsx
  src/module/market/template/index.tsx
  src/module/quest/template/QuestDetailTemplate.tsx
  src/page/quest/detail/index.tsx
  src/page/quiz/quiz-play/index.tsx
Labels: 은비, 🎨 ui
